
services:
  backend:
    image: backend1
    container_name: backend
    ports:
      - "5001:5001"
    networks:
      - coursify-network
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017 
    depends_on:
      - mongo

  frontend:
    image: frontend1
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - coursify-network 
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - coursify-network 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

networks:
  coursify-network: 
    driver: bridge