FROM node:20-slim

COPY . .

RUN npm install

ENV RESTREVIEWS_DB_URI=mongodb://admin:password@192.168.1.101:27017  RESTREVIEWS_NS=sample_restaurants PORT=5000

EXPOSE 5001

CMD [ "npm" , "run" , "start"]